//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QoalaWS.DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccessControl
    {
        public string TOKEN { get; set; }
        public System.DateTime CREATED_AT { get; set; }
        public Nullable<System.DateTime> EXPIRED_AT { get; set; }
        public string REMOTEIP { get; set; }
        public decimal ID_USER { get; set; }
    
        public virtual User USER { get; set; }
    }
}
