//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QoalaWS.DAO
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class ACCESSCONTROL
    {
        [Required(ErrorMessage = "Token é obrigatório")]
        public string TOKEN { get; set; }

        [Required(ErrorMessage = "Data de criação é obrigatório")]
        public System.DateTime CREATED_AT { get; set; }

        [Required(ErrorMessage = "Data de expiração é obrigatório")]
        public Nullable<System.DateTime> EXPIRED_AT { get; set; }
        public string REMOTEIP { get; set; }

        [Required(ErrorMessage = "ID User é obrigatório")]
        public decimal ID_USER { get; set; }
    
        public virtual USER USER { get; set; }
    }
}
