//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QoalaWS.DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class DEVICES
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DEVICES()
        {
            this.DEVICE_GEO_LOCATIONS = new HashSet<DEVICE_GEO_LOCATIONS>();
        }
    
        public decimal ID_DEVICE { get; set; }
        public string ALIAS { get; set; }
        public string COLOR { get; set; }
        public decimal FREQUENCY_UPDATE { get; set; }
        public Nullable<decimal> LAST_LONGITUDE { get; set; }
        public Nullable<decimal> LAST_LATITUDE { get; set; }
        public Nullable<bool> ALARM { get; set; }
        public decimal USER_ID { get; set; }
        public System.DateTime CREATED_AT { get; set; }
        public Nullable<System.DateTime> UPDATED_AT { get; set; }
        public Nullable<System.DateTime> DELETED_AT { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DEVICE_GEO_LOCATIONS> DEVICE_GEO_LOCATIONS { get; set; }
        public virtual USERS USERS { get; set; }
    }
}
