//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QoalaWS.DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class DEVICE_LOGS
    {
        public string LOG { get; set; }
        public decimal DEVICE_ID { get; set; }
        public System.DateTime CREATED_AT { get; set; }
    }
}
