//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QoalaWS.DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class NET_ACCOUNTS
    {
        public string ACCESS_TOKEN_ID { get; set; }
        public decimal USER_ID { get; set; }
        public string IDENTIFIER { get; set; }
        public string PROVIDER { get; set; }
    }
}
