//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QoalaWS.DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Plan
    {
        public decimal ID_PLAN { get; set; }
        public string NAME { get; set; }
        public decimal PRICE_CENTS { get; set; }
        public decimal LEFT { get; set; }
        public string REWARDS { get; set; }
        public System.DateTime CREATED_AT { get; set; }
    }
}
