//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QoalaWS.DAO
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QoalaEntities : DbContext
    {
        public QoalaEntities()
            : base("name=QoalaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<COMMENT> COMMENTS { get; set; }
        public virtual DbSet<DEVICE_GEO_LOCATIONS> DEVICE_GEO_LOCATIONS { get; set; }
        public virtual DbSet<DEVICE> DEVICES { get; set; }
        public virtual DbSet<NET_ACCOUNTS> NET_ACCOUNTS { get; set; }
        public virtual DbSet<POST> POSTS { get; set; }
        public virtual DbSet<USER> USERS { get; set; }
        public virtual DbSet<COMMENT_LOGS> COMMENT_LOGS { get; set; }
        public virtual DbSet<DEVICE_GEO_LOCATION_LOGS> DEVICE_GEO_LOCATION_LOGS { get; set; }
        public virtual DbSet<DEVICE_LOGS> DEVICE_LOGS { get; set; }
        public virtual DbSet<POST_LOGS> POST_LOGS { get; set; }
        public virtual DbSet<USER_LOGS> USER_LOGS { get; set; }
    }
}
