//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QoalaWS.DAO
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class USER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public USER()
        {
            this.COMMENTS = new HashSet<COMMENT>();
            this.DEVICES = new HashSet<DEVICE>();
            this.POSTS = new HashSet<POST>();
            this.ACCESSCONTROLs = new HashSet<ACCESSCONTROL>();
        }
    
        public decimal ID_USER { get; set; }

        [Required(ErrorMessage = "Nome é obrigatório")]
        public string NAME { get; set; }

        [Required(ErrorMessage = "Senha é obrigatório")]
        public string PASSWORD { get; set; }

        [Required(ErrorMessage = "Email é obrigatório")]
        public string EMAIL { get; set; }

        public byte PERMISSION { get; set; }

        public System.DateTime CREATED_AT { get; set; }

        public Nullable<System.DateTime> UPDATED_AT { get; set; }
        public Nullable<System.DateTime> DELETED_AT { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<COMMENT> COMMENTS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DEVICE> DEVICES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<POST> POSTS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ACCESSCONTROL> ACCESSCONTROLs { get; set; }
    }
}

